In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/marine_engine_fault_dataset (1).csv')
data.head()

,Timestamp,Shaft_RPM,Engine_Load,Fuel_Flow,Air_Pressure,Ambient_Temp,Oil_Temp,Oil_Pressure,Vibration_X,Vibration_Y,Vibration_Z,Fault_Label,Cylinder1_Pressure,Cylinder1_Exhaust_Temp,Cylinder2_Pressure,Cylinder2_Exhaust_Temp,Cylinder3_Pressure,Cylinder3_Exhaust_Temp,Cylinder4_Pressure,Cylinder4_Exhaust_Temp
0,2024-01-01 00:00:00,965.414073,72.397307,114.665107,1.025896,27.055404,73.000474,3.407503,0.087248,0.076305,0.069988,0,157.710104,418.761079,139.335694,449.428109,151.140472,400.142839,138.194303,469.788241
1,2024-01-01 00:00:01,996.888052,90.818713,156.425262,1.258291,26.686902,77.039208,2.935203,0.035802,0.066677,0.077774,0,163.301036,416.912327,151.742643,383.042000,147.326823,400.557809,131.104323,430.206873
2,2024-01-01 00:00:02,948.424675,76.358257,126.188656,1.184234,25.482428,79.076912,3.942825,0.102402,0.047158,0.046104,0,148.868866,455.707882,155.441964,374.099103,131.471313,455.522306,143.895843,417.453433
3,2024-01-01 00:00:03,982.370968,63.822324,107.840402,1.150488,24.372997,78.028895,3.893302,0.065176,0.067617,0.041622,0,142.861369,464.990838,137.514280,407.003480,154.426397,423.237676,145.149830,383.834081
4,2024-01-01 00:00:04,973.166374,69.483056,113.637069,1.174918,30.678317,78.353818,3.518891,0.047297,0.085649,0.093252,0,138.080575,407.992398,144.795201,482.424962,152.438065,427.269295,162.077661,450.501985

In [ ]:
data.isnull().sum()
data = data.dropna()
data
data = data.drop_duplicates()
data

,Timestamp,Shaft_RPM,Engine_Load,Fuel_Flow,Air_Pressure,Ambient_Temp,Oil_Temp,Oil_Pressure,Vibration_X,Vibration_Y,Vibration_Z,Fault_Label,Cylinder1_Pressure,Cylinder1_Exhaust_Temp,Cylinder2_Pressure,Cylinder2_Exhaust_Temp,Cylinder3_Pressure,Cylinder3_Exhaust_Temp,Cylinder4_Pressure,Cylinder4_Exhaust_Temp
0,2024-01-01 00:00:00,965.414073,72.397307,114.665107,1.025896,27.055404,73.000474,3.407503,0.087248,0.076305,0.069988,0,157.710104,418.761079,139.335694,449.428109,151.140472,400.142839,138.194303,469.788241
1,2024-01-01 00:00:01,996.888052,90.818713,156.425262,1.258291,26.686902,77.039208,2.935203,0.035802,0.066677,0.077774,0,163.301036,416.912327,151.742643,383.042000,147.326823,400.557809,131.104323,430.206873
2,2024-01-01 00:00:02,948.424675,76.358257,126.188656,1.184234,25.482428,79.076912,3.942825,0.102402,0.047158,0.046104,0,148.868866,455.707882,155.441964,374.099103,131.471313,455.522306,143.895843,417.453433
3,2024-01-01 00:00:03,982.370968,63.822324,107.840402,1.150488,24.372997,78.028895,3.893302,0.065176,0.067617,0.041622,0,142.861369,464.990838,137.514280,407.003480,154.426397,423.237676,145.149830,383.834081
4,2024-01-01 00:00:04,973.166374,69.483056,113.637069,1.174918,30.678317,78.353818,3.518891,0.047297,0.085649,0.093252,0,138.080575,407.992398,144.795201,482.424962,152.438065,427.269295,162.077661,450.501985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024-01-01 02:46:35,927.425457,87.725739,111.499731,1.113578,22.750387,80.476350,3.405024,0.060880,0.038950,0.083647,0,156.744246,433.514089,131.863489,385.564915,142.939393,488.531652,160.730329,429.839846
9996,2024-01-01 02:46:36,996.372362,64.716126,143.344425,1.188479,27.202907,81.488747,3.746873,0.068109,0.038700,0.021936,0,127.299007,449.949988,154.616035,428.006118,138.444477,438.231183,153.707112,450.274664
9997,2024-01-01 02:46:37,921.728914,34.614266,114.287530,1.187564,23.849295,82.763312,3.349990,0.054361,0.066472,0.064506,0,165.110101,415.394811,170.056102,471.034358,148.002473,432.060190,128.142606,413.039316
9998,2024-01-01 02:46:38,940.193390,75.633493,159.528062,1.178307,27.049806,81.636159,2.754986,0.038497,0.075067,0.061815,0,154.966481,424.032166,148.744202,385.815896,133.609915,433.157294,141.792309,382.778918
9999,2024-01-01 02:46:39,963.846229,71.444945,141.138450,1.065738,31.385956,80.273322,3.012553,0.058376,0.050167,0.088747,0,147.582393,387.016775,137.177686,360.048941,149.848392,433.975209,154.095358,439.516794

In [23]:
x = data.drop(['Timestamp', 'Fault_Label'], axis=1).values
y = data['Fault_Label'].values

In [ ]:
print(x)
print(y)

[['2024-01-01 00:00:00' 965.4140726802144 72.39730688423849 ...
  400.1428388267937 138.19430254740075 469.7882410713132]
 ['2024-01-01 00:00:01' 996.8880520879256 90.81871276917543 ...
  400.557808511954 131.10432307531437 430.20687303491377]
 ['2024-01-01 00:00:02' 948.4246746121972 76.35825740705137 ...
  455.5223061688783 143.89584259034743 417.4534329813856]
 ...
 ['2024-01-01 02:46:37' 921.7289143251588 34.61426604035569 ...
  432.060189951417 128.14260624410693 413.0393161930157]
 ['2024-01-01 02:46:38' 940.1933900886902 75.63349315006228 ...
  433.15729361963696 141.79230890875328 382.7789183762849]
 ['2024-01-01 02:46:39' 963.846228628674 71.4449449568007 ...
  433.9752086766964 154.09535790617622 439.5167943343973]]
[0 0 0 ... 0 0 0]

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

classification = LogisticRegression(max_iter=1000)

classification.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = classification.predict(x_test)

print(y_pred)

[0 0 0 ... 0 0 5]

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 0.8525

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[1273   10   11    8    0    2    3    0]
 [  99    6    2    1    0    0    0    0]
 [  83    0   16    0    0    0    0    0]
 [  64    0    2   21    0    1    0    0]
 [   0    0    0    0  107    0    0    0]
 [   5    0    0    0    0   89    0    0]
 [   3    0    0    0    0    0   95    0]
 [   0    0    0    0    0    1    0   98]]

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.90      1307
           1       0.38      0.06      0.10       108
           2       0.52      0.16      0.25        99
           3       0.70      0.24      0.36        88
           4       1.00      1.00      1.00       107
           5       0.96      0.95      0.95        94
           6       0.97      0.97      0.97        98
           7       1.00      0.99      0.99        99

    accuracy                           0.85      2000
   macro avg       0.79      0.67      0.69      2000
weighted avg       0.82      0.85      0.82      2000

In [16]:
data.isnull().sum()
data = data.dropna()
data
data = data.drop_duplicates()
data

,Timestamp,Shaft_RPM,Engine_Load,Fuel_Flow,Air_Pressure,Ambient_Temp,Oil_Temp,Oil_Pressure,Vibration_X,Vibration_Y,Vibration_Z,Fault_Label,Cylinder1_Pressure,Cylinder1_Exhaust_Temp,Cylinder2_Pressure,Cylinder2_Exhaust_Temp,Cylinder3_Pressure,Cylinder3_Exhaust_Temp,Cylinder4_Pressure,Cylinder4_Exhaust_Temp
0,2024-01-01 00:00:00,965.414073,72.397307,114.665107,1.025896,27.055404,73.000474,3.407503,0.087248,0.076305,0.069988,0.0,157.710104,418.761079,139.335694,449.428109,151.140472,400.142839,138.194303,469.788241
1,2024-01-01 00:00:01,996.888052,90.818713,156.425262,1.258291,26.686902,77.039208,2.935203,0.035802,0.066677,0.077774,0.0,163.301036,416.912327,151.742643,383.042000,147.326823,400.557809,131.104323,430.206873
2,2024-01-01 00:00:02,948.424675,76.358257,126.188656,1.184234,25.482428,79.076912,3.942825,0.102402,0.047158,0.046104,0.0,148.868866,455.707882,155.441964,374.099103,131.471313,455.522306,143.895843,417.453433
3,2024-01-01 00:00:03,982.370968,63.822324,107.840402,1.150488,24.372997,78.028895,3.893302,0.065176,0.067617,0.041622,0.0,142.861369,464.990838,137.514280,407.003480,154.426397,423.237676,145.149830,383.834081
4,2024-01-01 00:00:04,973.166374,69.483056,113.637069,1.174918,30.678317,78.353818,3.518891,0.047297,0.085649,0.093252,0.0,138.080575,407.992398,144.795201,482.424962,152.438065,427.269295,162.077661,450.501985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5820,2024-01-01 01:37:00,932.579446,58.263796,148.744817,1.151816,27.121451,79.121190,3.691840,0.046415,0.067902,0.071123,2.0,143.630356,390.723681,128.149077,422.600781,139.383151,418.682565,164.859063,424.360757
5821,2024-01-01 01:37:01,999.969500,78.932299,105.456334,1.137139,25.887581,82.283540,3.428975,0.110187,0.065606,0.061508,1.0,136.948968,436.291380,138.997565,421.162704,134.444657,381.772575,147.472103,356.752226
5822,2024-01-01 01:37:02,984.283509,95.429824,122.683733,0.417224,26.262266,82.829217,3.559150,0.007660,0.057282,0.085275,6.0,145.831770,378.757988,143.968507,403.739662,129.554367,367.462965,149.072822,448.433162
5823,2024-01-01 01:37:03,1014.150665,64.762358,141.576027,1.013439,30.974493,80.545393,4.183460,0.058902,0.034449,0.072674,0.0,156.576267,476.043765,141.546422,450.669859,144.858062,391.275377,142.278380,444.785245
5824,2024-01-01 01:37:04,887.821283,71.659219,141.569636,1.187790,29.321148,88.791587,3.237615,0.084980,0.061355,0.071900,0.0,120.623854,447.624957,154.066624,417.824286,137.680802,444.807941,137.335944,420.849978

In [18]:
x = data.drop(data.columns[11], axis=1).values

y = data.iloc[:,11].values
x,y

(array([['2024-01-01 00:00:00', 965.4140726802144, 72.39730688423849, ...,
         400.1428388267937, 138.19430254740075, 469.7882410713132],
        ['2024-01-01 00:00:01', 996.8880520879256, 90.81871276917543, ...,
         400.557808511954, 131.10432307531437, 430.20687303491377],
        ['2024-01-01 00:00:02', 948.4246746121972, 76.35825740705137, ...,
         455.5223061688783, 143.89584259034743, 417.4534329813856],
        ...,
        ['2024-01-01 01:37:02', 984.2835093303048, 95.42982397625502, ...,
         367.4629654887221, 149.07282211326344, 448.4331619695417],
        ['2024-01-01 01:37:03', 1014.1506650074244, 64.7623577035802, ...,
         391.275377210284, 142.27837963891412, 444.78524544889],
        ['2024-01-01 01:37:04', 887.8212826776776, 71.6592186150978, ...,
         444.8079406515805, 137.33594390991075, 420.8499778860996]],
       dtype=object),
 array([0., 0., 0., ..., 6., 0., 0.]))

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

rf = RandomForestClassifier(n_estimators=100, random_state=42)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy : 0.8909871244635194
[[763   7   5   3   0   4   1   0]
 [ 54   5   0   1   0   0   0   0]
 [ 26   0  27   1   0   0   0   0]
 [ 19   0   0  26   0   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  3   0   0   0   0  51   0   0]
 [  3   0   0   0   0   0  52   0]
 [  0   0   0   0   0   0   0  58]]
              precision    recall  f1-score   support

         0.0       0.88      0.97      0.92       783
         1.0       0.42      0.08      0.14        60
         2.0       0.84      0.50      0.63        54
         3.0       0.84      0.58      0.68        45
         4.0       1.00      1.00      1.00        56
         5.0       0.93      0.94      0.94        54
         6.0       0.98      0.95      0.96        55
         7.0       1.00      1.00      1.00        58

    accuracy                           0.89      1165
   macro avg       0.86      0.75      0.78      1165
weighted avg       0.87      0.89      0.87      1165

In [27]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [28]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

xgb = XGBClassifier(random_state=42)

xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy : 0.8849785407725322
[[762  11   5   2   0   1   2   0]
 [ 54   6   0   0   0   0   0   0]
 [ 30   0  23   1   0   0   0   0]
 [ 19   0   0  26   0   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  6   0   0   0   0  48   0   0]
 [  3   0   0   0   0   0  52   0]
 [  0   0   0   0   0   0   0  58]]
              precision    recall  f1-score   support

         0.0       0.87      0.97      0.92       783
         1.0       0.35      0.10      0.16        60
         2.0       0.82      0.43      0.56        54
         3.0       0.90      0.58      0.70        45
         4.0       1.00      1.00      1.00        56
         5.0       0.98      0.89      0.93        54
         6.0       0.96      0.95      0.95        55
         7.0       1.00      1.00      1.00        58

    accuracy                           0.88      1165
   macro avg       0.86      0.74      0.78      1165
weighted avg       0.87      0.88      0.87      1165

In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy : 0.8223175965665236
[[684  44  38  13   0   1   3   0]
 [ 42  11   4   3   0   0   0   0]
 [ 26   1  25   2   0   0   0   0]
 [ 20   1   0  24   0   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  5   0   0   0   0  49   0   0]
 [  2   1   0   0   0   0  52   0]
 [  0   0   0   0   0   0   1  57]]
              precision    recall  f1-score   support

         0.0       0.88      0.87      0.88       783
         1.0       0.19      0.18      0.19        60
         2.0       0.37      0.46      0.41        54
         3.0       0.57      0.53      0.55        45
         4.0       1.00      1.00      1.00        56
         5.0       0.98      0.91      0.94        54
         6.0       0.93      0.95      0.94        55
         7.0       1.00      0.98      0.99        58

    accuracy                           0.82      1165
   macro avg       0.74      0.74      0.74      1165
weighted avg       0.83      0.82      0.82      1165

In [30]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

svm = SVC(kernel='rbf')

svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy : 0.6721030042918454
[[783   0   0   0   0   0   0   0]
 [ 60   0   0   0   0   0   0   0]
 [ 54   0   0   0   0   0   0   0]
 [ 45   0   0   0   0   0   0   0]
 [ 56   0   0   0   0   0   0   0]
 [ 54   0   0   0   0   0   0   0]
 [ 55   0   0   0   0   0   0   0]
 [ 58   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

         0.0       0.67      1.00      0.80       783
         1.0       0.00      0.00      0.00        60
         2.0       0.00      0.00      0.00        54
         3.0       0.00      0.00      0.00        45
         4.0       0.00      0.00      0.00        56
         5.0       0.00      0.00      0.00        54
         6.0       0.00      0.00      0.00        55
         7.0       0.00      0.00      0.00        58

    accuracy                           0.67      1165
   macro avg       0.08      0.12      0.10      1165
weighted avg       0.45      0.67      0.54      1165

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [31]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy : 0.6832618025751073
[[767   5   3   2   1   1   2   2]
 [ 58   1   0   0   0   0   1   0]
 [ 53   0   1   0   0   0   0   0]
 [ 22   0   0  15   0   0   1   7]
 [ 54   0   0   0   1   0   1   0]
 [ 51   0   1   0   1   0   0   1]
 [ 52   1   0   1   0   0   0   1]
 [ 30   0   0  17   0   0   0  11]]
              precision    recall  f1-score   support

         0.0       0.71      0.98      0.82       783
         1.0       0.14      0.02      0.03        60
         2.0       0.20      0.02      0.03        54
         3.0       0.43      0.33      0.38        45
         4.0       0.33      0.02      0.03        56
         5.0       0.00      0.00      0.00        54
         6.0       0.00      0.00      0.00        55
         7.0       0.50      0.19      0.28        58

    accuracy                           0.68      1165
   macro avg       0.29      0.19      0.20      1165
weighted avg       0.55      0.68      0.58      1165